const esc=v=>String(v??"—").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const pretty=v=>JSON.stringify(v??{},null,2);
const fmt=v=>v==null?"—":Number(v).toLocaleString("en",{maximumFractionDigits:1});
let data,currentScenario;
function badge(v){const cls=["GREEN","PREFERRED"].includes(v)?"green":["LIGHT_GREEN","ACCEPTABLE_SAFE_ALTERNATIVE"].includes(v)?"light-green":v==="YELLOW_INFORMATION_GAP"?"yellow":"red";return `<span class="status ${cls}">${esc(v)}</span>`}
function localCounts(c={}){return `G ${c.GREEN||0} · LG ${c.LIGHT_GREEN||0} · Y ${c.YELLOW_INFORMATION_GAP||0} · R ${c.RED_MODEL_ERROR||0}`}
function globalCounts(c={}){return `P ${c.PREFERRED||0} · A ${c.ACCEPTABLE_SAFE_ALTERNATIVE||0} · M ${c.MISMATCH||0}`}
function renderMain(){
 const d=data.business_decision,a=data.fresh_audit;
 document.querySelector("#decision-card").innerHTML=`<h3>Converged decision</h3><p><strong>Best FR:</strong> ${esc(d.best_fr)}</p><p>${esc(d.basis)}</p><p><strong>Architecture B:</strong> ${d.qwen_b_genuine_errors} genuine errors versus ${d.qwen_a_genuine_errors} for A; not justified.</p><p><strong>Fresh audit:</strong> ${a.critical_calls_audited} A/B calls · ${a.other_model_changed_calls_audited} changed other-model calls · ${a.other_model_unchanged_ranking_samples} ranking samples · no material finding.</p>`;
 document.querySelector("#architecture-table").innerHTML=`<div class="table-wrap"><table><thead><tr><th>Architecture / model</th><th>Scope</th><th>LOCAL G/LG/Y/R</th><th>GLOBAL P/A/M</th><th>Info gaps</th><th>Data defects</th><th>Ambiguous</th><th>Excluded</th><th>Genuine errors</th><th>Legacy raw / effective</th><th>Gate changes</th><th>Decision</th></tr></thead><tbody>${data.architectures.map(x=>x.id==="C"?`<tr><td><strong>${esc(x.name)}</strong><br>${esc(x.model)}</td><td>${esc(x.scope)}</td><td colspan="9">—</td><td>${esc(x.decision)}</td></tr>`:`<tr><td><strong>${esc(x.name)}</strong><br><span class="muted">${esc(x.model)}</span></td><td>${esc(x.scope)}</td><td>${esc(localCounts(x.local))}</td><td>${esc(globalCounts(x.global))}</td><td>${x.information_gaps}</td><td>${x.data_defect_calls}</td><td>${x.contract_ambiguity_calls}</td><td>${x.excluded_defective_or_ambiguous}</td><td>${x.genuine_model_errors}</td><td>${x.legacy_raw_compatible}/180 · ${x.legacy_effective_compatible}/180</td><td>${x.external_gate_changes}</td><td>${esc(x.decision)}</td></tr>`).join("")}</tbody></table></div>`;
 document.querySelector("#scenario-grid").innerHTML=data.scenarios.map(s=>`<a class="scenario-card" href="#scenario=${esc(s.id)}"><h3>${esc(s.id)}</h3><p>${esc(s.mission)}</p><dl><dt>Calls</dt><dd>${s.models.reduce((n,m)=>n+m.calls,0)}</dd><dt>Qwen3 1.7B</dt><dd>${esc(localCounts(s.models[0].local))}</dd><dt>Architecture B</dt><dd>${esc(localCounts(s.models[4].local))}</dd><dt>Case range</dt><dd>000–029</dd></dl></a>`).join("");
 document.querySelector("#provenance").innerHTML=`<dl class="provenance-list"><dt>Identity</dt><dd>${esc(data.canonical.id)} · ${data.canonical.observations} observations · ${data.canonical.clock}</dd><dt>Calls</dt><dd>${data.corrected_evaluation.call_count} existing FR calls · candidate inference rerun NO</dd><dt>Replay</dt><dd>${esc(data.open_loop_warning)}</dd><dt>Manifest</dt><dd>${esc(data.canonical.manifest_sha256)}</dd><dt>Scheduler</dt><dd>${esc(data.canonical.scheduler_sha256)}</dd><dt>Timing</dt><dd>${esc(data.canonical.timing_label)}</dd><dt>Evaluator</dt><dd>${esc(data.corrected_evaluation.schema_version)} · legacy bounded reference is compatibility-only</dd><dt>Raw source hashes</dt><dd>${esc(pretty(data.corrected_evaluation.source_hashes))}</dd></dl>`;
}
function renderScenarioRows(){
 const filter=document.querySelector("#case-filter").value;
 const rows=data.cases.filter(c=>c.episode_id===currentScenario.id&&(filter==="all"||c.case_flags[filter]));
 document.querySelector("#filter-count").textContent=`${rows.length}/30 cases`;
 document.querySelector("#scenario-table").innerHTML=`<div class="table-wrap"><table><thead><tr><th>Second / frame</th><th>Exact available sensor/audio evidence</th>${currentScenario.models.map(m=>`<th>${esc(m.model)}<br>LOCAL / GLOBAL</th>`).join("")}</tr></thead><tbody>${rows.map(c=>`<tr><td><a class="case-link" href="#case=${esc(c.id)}">t=${c.source_time_s}s · ${esc(c.id)}</a><img class="thumb" src="${esc(c.image)}" alt="${esc(c.id)}"></td><td>${esc(c.sensor_text)}<br><span class="muted">Audio: ${c.audio_history.length?c.audio_history.map(x=>esc(x.transcript)).join(" · "):"none"}</span><br><span class="muted">Flags: ${Object.entries(c.case_flags).filter(x=>x[1]).map(x=>esc(x[0])).join(" · ")||"none"}</span></td>${c.evaluations.map(e=>`<td>${esc(e.raw_output.direction)}<br>${badge(e.local_verdict)}<br>${badge(e.global_status)}${e.genuine_model_error?"<br><strong>genuine error</strong>":""}${e.information_gap?"<br><strong>information gap</strong>":""}${e.data_defect?"<br><strong>data defect</strong>":""}${e.contract_ambiguity?"<br><strong>contract ambiguity</strong>":""}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;
}
function showScenario(id){
 currentScenario=data.scenarios.find(s=>s.id===id);if(!currentScenario){location.hash="";return}
 document.querySelector("#main-view").hidden=true;document.querySelector("#case-view").hidden=true;document.querySelector("#scenario-view").hidden=false;
 document.querySelector("#scenario-heading").innerHTML=`<div class="eyebrow">${esc(id)} · 30 seconds · 150 calls</div><h2>${esc(currentScenario.mission)}</h2><p>${currentScenario.models.map(m=>`${esc(m.model)}: ${esc(localCounts(m.local))} · global ${esc(globalCounts(m.global))}`).join("<br>")}</p><p class="warning"><strong>OPEN-LOOP:</strong> later prerecorded observations are not caused by these outputs.</p>`;
 document.querySelector("#case-filter").value="all";renderScenarioRows();document.title=`${id} · S42 Model Lab`;scrollTo(0,0);
}
function evaluationCard(e){
 const legacy=e.legacy_bounded_compatibility,v=e.vision_context_review,g=e.global_semantic_judgment;
 return `<section class="evidence-card"><h3>${esc(e.architecture)} · ${esc(e.model)}</h3><p>LOCAL ${badge(e.local_verdict)} GLOBAL ${badge(e.global_status)}</p><p><strong>Genuine model error:</strong> ${e.genuine_model_error?"YES":"NO"} · <strong>excluded:</strong> ${e.excluded_from_model_training_counts?"YES":"NO"}</p><p><strong>Information gap:</strong> ${e.information_gap?"YES":"NO"}${e.information_gap_detail?` · ${esc(e.information_gap_detail.absent_fact)}`:""}</p><p><strong>Data defect:</strong> ${e.data_defect?"YES":"NO"} · <strong>Contract ambiguity:</strong> ${e.contract_ambiguity?"YES":"NO"}</p><p>${esc(e.reason.local)}</p><p>${esc(e.reason.global)}</p><dl class="facts"><dt>Raw → effective</dt><dd>${esc(e.raw_output.direction)} → ${esc(e.effective_output.direction)}</dd><dt>External gate</dt><dd>${esc(e.effective_output.gate_disposition)}</dd><dt>Preferred action</dt><dd>${esc(g.full_reference_preferred_action.action)} · ${esc(g.full_reference_preferred_action.reason)}</dd><dt>Legacy bounded compatibility</dt><dd>${legacy.raw_compatible?"raw yes":"raw no"} · ${legacy.effective_compatible?"effective yes":"effective no"} · ${esc(legacy.label)}</dd><dt>Timing</dt><dd>mini-PC ${fmt(e.raw_output.latency_ms)} ms · request ${e.timing.request_time_s}s · estimated Orin base ${fmt(e.timing.estimated_orin_nx_16gb.availability_time_s.base_s)}s</dd></dl>${v?`<details open><summary>Consumed Vision source / age / truth / freshness / relevance</summary><pre>${esc(pretty(v))}</pre></details>`:""}<details open><summary>Full FR preferred action, accepted alternatives and grading note</summary><pre>${esc(pretty({preferred:g.full_reference_preferred_action,accepted_alternatives:g.full_reference_accepted_alternatives,grading_note:g.full_reference_grading_note}))}</pre></details><details open><summary>Exact FR input</summary><pre>${esc(pretty(e.exact_fr_input))}</pre></details><details><summary>Exact raw output</summary><pre>${esc(pretty(e.raw_output))}</pre></details><details><summary>Defect / ambiguity ledger</summary><pre>${esc(pretty({data_defects:e.data_defects,contract_ambiguities:e.contract_ambiguities,model_culpability_reason:e.model_culpability_reason}))}</pre></details><details><summary>Effective/gated output and timing</summary><pre>${esc(pretty({effective_output:e.effective_output,external_gate:e.external_gate,timing:e.timing}))}</pre></details></section>`;
}
function showCase(id){
 const c=data.cases.find(x=>x.id===id);if(!c){location.hash="";return}
 document.querySelector("#main-view").hidden=true;document.querySelector("#scenario-view").hidden=true;document.querySelector("#case-view").hidden=false;document.querySelector("#case-back").onclick=()=>{location.hash=`scenario=${c.episode_id}`};
 document.querySelector("#case-content").innerHTML=`<p class="warning"><strong>OPEN-LOOP REPLAY:</strong> ${esc(data.open_loop_warning)}</p><div class="case-hero"><div><img src="${esc(c.image)}" alt="${esc(c.id)}"><p class="mono">${esc(c.image_sha256)}</p></div><div><div class="eyebrow">${esc(c.id)} · source t=${c.source_time_s}s · five FR calls</div><h2>${esc(c.mission)}</h2><p><strong>Motion posture:</strong> ${esc(c.mission_motion_posture)}</p><p class="sensor">${esc(c.sensor_text)}</p><h3>Completed audio available now</h3>${c.audio_history.length?`<ul class="audio-list">${c.audio_history.map(x=>`<li>${esc(x.transcript)} · ${esc(x.intent)} · ${esc(x.status)} · source ${x.source_end_time_s}s · age ${x.age_s}s</li>`).join("")}</ul>`:"<p>None</p>"}<details><summary>Full enriched + original sensors</summary><pre>${esc(pretty(c.sensors))}</pre></details><details open><summary>Full FR and FV oracle</summary><pre>${esc(pretty(c.full_reference))}</pre></details><details><summary>Historical bounded compatibility — legacy only</summary><pre>${esc(pretty(c.legacy_bounded_action_reference))}</pre></details></div></div><div class="evidence-grid">${c.evaluations.map(evaluationCard).join("")}</div>`;
 document.title=`${id} · S42 Model Lab`;scrollTo(0,0);
}
function route(){const [kind,value]=location.hash.slice(1).split("=",2);if(kind==="scenario"){showScenario(value);return}if(kind==="case"){showCase(value);return}document.querySelector("#main-view").hidden=false;document.querySelector("#scenario-view").hidden=true;document.querySelector("#case-view").hidden=true;document.title="Edge AI Training · Model Lab";scrollTo(0,0)}
document.querySelector("#case-filter").addEventListener("change",renderScenarioRows);
document.querySelectorAll("[data-back]").forEach(x=>x.onclick=()=>{location.hash=""});window.addEventListener("hashchange",route);
fetch("s41-results.json").then(r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}).then(x=>{data=x;renderMain();route()}).catch(e=>document.body.innerHTML=`<p class="wrap">Could not load S42 evidence: ${esc(e.message)}</p>`);
